[package]
name = "nes_code"
version = "0.1.0"
authors = ["bugzmanov <bugzmanov@gmail.com>", "dzwduan <dzwduan@gmail.com>"]
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
